# Generated by Django 3.1 on 2024-06-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_varuations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='varuations',
            new_name='variations',
        ),
    ]
